name: deploy
description: deploy

inputs:
  environment:
    required: true
  port:
    required: true
runs:
  using: composite
  steps:
    - name: clone repo
      uses: actions/checkout@v6
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
    - shell: bash
      run: echo "deploy"
    - name: venv
      shell: bash
      working-directory: python-greetings
      run: python3 -m venv venv
    - name: reqs
      shell: bash
      working-directory: python-greetings
      run: ./venv/bin/python -m pip install -r requirements.txt
    - name: stop
      shell: bash
      working-directory: python-greetings
      run: pm2 delete greetings-app-${{ inputs.environment }} || true
    - name: start
      shell: bash
      working-directory: python-greetings
      run: pm2 start app.py --name greetings-app-${{ inputs.environment }} --interpreter ./venv/bin/python -- --port ${{ inputs.port }}
    - name: fix???
      shell: bash
      run: pm2 save
    - name: done
      shell: bash
      run: echo deployed
