name: python-greetings

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: clone
        uses: actions/checkout@v6
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          clean: 'false'

      - name: pips
        uses: ./.github/actions/install-deps    
    
  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: clone
        uses: actions/checkout@v6
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          clean: 'false'

      - name: deploy
        uses: ./.github/actions/deploy
        with:
          environment: dev
          port: "7001"
    
  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: clone
        uses: actions/checkout@v6
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework
          clean: 'false'

      - name: tests
        uses: ./.github/actions/test
        with:
          environment: dev
    
  deploy-to-stg:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - name: Clone python-greetings repo
        uses: actions/checkout@v6
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          clean: 'false'

      - name: deploy
        uses: ./.github/actions/deploy
        with:
          environment: stg
          port: "7002"

  tests-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg
    steps:
      - name: clone
        uses: actions/checkout@v6
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework
          clean: 'false'

      - name: tests
        uses: ./.github/actions/test
        with:
          environment: stg
    
  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-stg
    steps:
      - name: clone
        uses: actions/checkout@v6
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          clean: 'false'

      - name: deploy
        uses: ./.github/actions/deploy
        with:
          environment: preprod
          port: "7003"    
    
  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - name: clone
        uses: actions/checkout@v6
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework
          clean: 'false'

      - name: tests
        uses: ./.github/actions/test
        with:
          environment: preprod    
    
  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - name: clone
        uses: actions/checkout@v6
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          clean: 'false'

      - name: deploy
        uses: ./.github/actions/deploy
        with:
          environment: prod
          port: "7004"

    
  Tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - name: clone
        uses: actions/checkout@v6
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework
          clean: 'false'

      - name: tests
        uses: ./.github/actions/test
        with:
          environment: prod
